#!/usr/bin/env python3
from __future__ import annotations

import re
from pathlib import Path
from datetime import datetime

# --- CONFIG -------------------------------------------------

TERMINAL_LOGS = Path("/mnt/c/Users/anmar/AppData/Roaming/MetaQuotes/Terminal/47AEB69EDDAD4D73097816C71FB25856/logs")
TESTER_LOGS   = Path("/mnt/c/Users/anmar/AppData/Roaming/MetaQuotes/Terminal/47AEB69EDDAD4D73097816C71FB25856/Tester/logs")

WORKSPACE = Path.home() / "openclaw" / "workspace"
OUT_DIR = WORKSPACE / "memory"

CONTEXT_BEFORE = 5
CONTEXT_AFTER  = 8

PATTERNS = [
    r"invalid stops",
    r"EX03 SLTP:",
    r"retDesc=", 
    r"invalid stop",
    r"trade context",
    r"\bret=\d+\b",
    r"\blasterr=\d+\b",
    r"\berr(or)?\b",
    r"failed",
    r"ordersend",
    r"ctrade::ordersend",
    r"modify",
    r"sl\b",
    r"\btp\b",
]

MAX_BYTES = 15 * 1024 * 1024  # 15 MB

# --- IMPLEMENTATION -----------------------------------------

def read_text_mt5(p: Path) -> list[str]:
    """
    MT5 .log files are often UTF-16 (wide chars). Try UTF-16 first, then UTF-8.
    """
    if not p.exists() or not p.is_file():
        return []
    try:
        if p.stat().st_size > MAX_BYTES:
            return [f"[SKIPPED: file too large: {p} ({p.stat().st_size} bytes)]"]
    except Exception:
        pass

    data = None
    for enc in ("utf-16", "utf-16-le", "utf-8"):
        try:
            data = p.read_text(encoding=enc, errors="replace")
            # quick sanity: if it still contains tons of NULs, it's wrong
            if "\x00" in data:
                continue
            break
        except Exception:
            continue

    if data is None:
        try:
            raw = p.read_bytes()
            data = raw.decode("utf-16", errors="replace")
        except Exception as e:
            return [f"[FAILED TO READ: {p} -> {e}]"]

    return data.splitlines()

def extract_blocks(lines: list[str], match_idxs: list[int], before: int, after: int) -> list[tuple[int, int]]:
    if not match_idxs:
        return []
    ranges = []
    for idx in match_idxs:
        s = max(0, idx - before)
        e = min(len(lines) - 1, idx + after)
        ranges.append((s, e))

    ranges.sort()
    merged = [ranges[0]]
    for s, e in ranges[1:]:
        ps, pe = merged[-1]
        if s <= pe + 1:
            merged[-1] = (ps, max(pe, e))
        else:
            merged.append((s, e))
    return merged

def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    rx = re.compile("(" + "|".join(PATTERNS) + ")", re.IGNORECASE)

    sources = [("TERMINAL", TERMINAL_LOGS), ("TESTER", TESTER_LOGS)]

    results: list[str] = []
    total_matches = 0
    files_scanned = 0
    files_with_hits = 0

    for kind, folder in sources:
        if not folder.exists():
            results.append(f"## {kind}\nFolder missing: `{folder}`\n")
            continue

        log_files = sorted(folder.glob("*.log"))
        results.append(f"## {kind}\nFolder: `{folder}`\nFiles found: **{len(log_files)}**\n")

        for p in log_files:
            files_scanned += 1
            lines = read_text_mt5(p)

            match_idxs = [i for i, line in enumerate(lines) if rx.search(line)]
            if not match_idxs:
                continue

            files_with_hits += 1
            total_matches += len(match_idxs)

            blocks = extract_blocks(lines, match_idxs, CONTEXT_BEFORE, CONTEXT_AFTER)

            results.append(f"### {kind} | {p.name}\nMatches: **{len(match_idxs)}**\n")
            for (s, e) in blocks:
                snippet = "\n".join([f"{j+1:5d}: {lines[j]}" for j in range(s, e + 1)])
                results.append("```text\n" + snippet + "\n```\n")

    ts = datetime.now().strftime("%Y-%m-%d_%H%M")
    out_path = OUT_DIR / f"LOGS_MT5_{ts}.md"

    header = [
        f"# MT5 Log Digest ({ts})",
        "",
        "Generated by `mt5_digest.py` (UTF-16 aware).",
        "",
        "## Scan Summary",
        f"- Terminal logs folder: `{TERMINAL_LOGS}`",
        f"- Tester logs folder: `{TESTER_LOGS}`",
        f"- Files scanned: **{files_scanned}**",
        f"- Files with hits: **{files_with_hits}**",
        f"- Total matched lines: **{total_matches}**",
        "",
        "## Patterns",
        "- " + "\n- ".join([f"`{p}`" for p in PATTERNS]),
        "",
        "---",
        "",
    ]

    out_path.write_text("\n".join(header + results), encoding="utf-8")
    print(f"Wrote: {out_path} (total matches: {total_matches})")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
